

USE lab_mysql;

CREATE TABLE CARS (
CAR_ID INT NOT NULL, 
MANUFACTURER VARCHAR(20), 
MODEL VARCHAR(20), 
YEAR CHAR(4), 
COLOR VARCHAR(10), 
DATE_SOLD DATE,
PRIMARY KEY(CAR_ID)
);

CREATE TABLE CUSTOMER (
CUSTOMER_ID INT NOT NULL AUTO_INCREMENT, 
NAME VARCHAR(30), 
ADDRESS VARCHAR(40), 
PHONE VARCHAR(20), 
CAR_ID INT, 
DATE_SOLD DATE, 
PRIMARY KEY (CUSTOMER_ID),
FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID)
);

CREATE TABLE INVOICE (
INVOICE_NR INT NOT NULL AUTO_INCREMENT, 
INV_DATE DATE, 
CAR_ID INT, 
CUSTOMER_ID INT, 
STAFF_ID INT,
PRIMARY KEY (INVOICE_NR) 
);

CREATE TABLE SALESPERSON (
STAFF_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY , 
NAME VARCHAR(30), 
ADDRESS VARCHAR(40),
OUTLET VARCHAR(20) 
);


ALTER TABLE INVOICE
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE INVOICE
ADD FOREIGN KEY(STAFF_ID) REFERENCES SALESPERSON(STAFF_ID);

ALTER TABLE INVOICE
ADD FOREIGN KEY(CAR_ID) REFERENCES CARS(CAR_ID);


