USE lab_mysql;

CREATE TABLE CARS (id INT AUTO_INCREMENT, CAR_ID INT PRIMARY KEY, MANUFACTURER VARCHAR(20), MODEL VARCHAR(20), YEAR CHAR(4), COLOR VARCHAR(10), DATE_SOLD DATE PRIMARY KEY);

CREATE TABLE CUSTOMER (id INT AUTO_INCREMENT, CUSTOMER_ID INT PRIMARY KEY, NAME VARCHAR(30), ADDRESS VARCHAR(40), PHONE VARCHAR(20), CAR_ID INT, DATE_SOLD DATE);

CREATE TABLE SALESPERSON (id INT AUTO_INCREMENT, STAFF_ID INT PRIMARY KEY, NAME VARCHAR(30), ADDRESS VARCHAR(40), OUTLET VARCHAR(20));

CREATE TABLE INVOICE (id INT AUTO_INCREMENT, INVOICE_NR INT PRIMARY KEY, INV_DATE DATE, CAR_ID INT, CUSTOMER_ID INT, STAFF_ID INT);

ALTER TABLE Cars
ADD FOREIGN KEY (CAR_ID) REFERENCES CUSTOMER(CAR_ID), INVOICE(CAR_ID);

ALTER TABLE CUSTOMER
ADD FOREIGN KEY (CUST_ID) REFERENCES INVOICE(CUST_ID);

ALTER TABLE SALESPERSON
ADD FOREIGN KEY (STAFF_ID) REFERENCES INVOICE(STAFF_ID);
