CREATE DATABASE lab_mysql;

USE lab_mysql;


CREATE TABLE Cars (
  ID INT NOT NULL PRIMARY KEY,
  VIN VARCHAR(17) NOT NULL,
  Manufacturer VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  Year INT NOT NULL,
  Color VARCHAR(50) NOT NULL
);


CREATE TABLE Customers (
  ID INT  NOT NULL PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Phone VARCHAR(20),
  Email VARCHAR(100),
  Address VARCHAR(100),
  City VARCHAR(50),
  StateProvince VARCHAR(50),
  Country VARCHAR(50),
  PostalCode VARCHAR(20)
);

CREATE TABLE Salespersons (
  ID INT  NOT NULL PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Store VARCHAR(100) NOT NULL
);

CREATE TABLE Invoices (
  ID INT NOT NULL PRIMARY KEY,
  InvoiceNumber VARCHAR(20) NOT NULL,
  InvoiceDate DATE NOT NULL,
  CarID INT UNSIGNED NOT NULL,
  CustomerID INT UNSIGNED NOT NULL,
  SalespersonID INT UNSIGNED NOT NULL,
  FOREIGN KEY (CarID) REFERENCES Cars(ID),
  FOREIGN KEY (CustomerID) REFERENCES Customers(ID),
  FOREIGN KEY (SalespersonID) REFERENCES Salespersons(ID)
);

