CREATE DATABASE lab_mysql;

USE lab_mysql;

DROP TABLE lab_mysql.cars;
CREATE TABLE lab_mysql.cars (
    CAR_KEY INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    VIN VARCHAR(20),
    MANUFACCTURER VARCHAR(20),
    MODEL VARCHAR(20),
    YEAR VARCHAR(4),
    COLOR VARCHAR(20)
);

DROP TABLE lab_mysql.customers;
CREATE TABLE lab_mysql.customers (
    CUSTOMER_KEY INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CUSTOMER_ID INT(20),
    NAME VARCHAR(100),
    PHONE VARCHAR(100),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(250),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CLUNTRY VARCHAR(50),
    ZIP_CODE VARCHAR(10)
);

DROP TABLE lab_mysql.salesperson;
CREATE TABLE lab_mysql.salesperson (
    STAF_KEY INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STAF_ID INT(20),
    NAME VARCHAR(100),
    STORE VARCHAR(50)
);

DROP TABLE lab_mysql.invoices;
CREATE TABLE lab_mysql.invoices (
    INVOICE_KEY INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    INVOICE_NUMBER INT(20),
    ORDER_DATE DATE,
    CAR_K INT UNIQUE,
    CUSTOMER_K INT UNIQUE,
    STAF_K INT UNIQUE,
    FOREIGN KEY (CAR_K) REFERENCES lab_mysql.car (CAR_KEY),
    FOREIGN KEY (CUSTOMER_K) REFERENCES lab_mysql.customers (CUSTOMER_KEY),
    FOREIGN KEY (STAF_K) REFERENCES lab_mysql.salesperson (STAF_KEY)
);