CREATE DATABASE lab_mysql;
USE lab_mysql;

CREATE TABLE cars (cars_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (cars_ID),
VIN VARCHAR(17) NOT NULL,
Manufacturer VARCHAR(10) NOT NULL,
 Model VARCHAR(25) NOT NULL,
 Year VARCHAR(4) NOT NULL,
 Color VARCHAR(10) NOT NULL)
 ;

CREATE TABLE customers (cust_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (cust_ID),
Customer_ID INT NOT NULL,
Name VARCHAR(20) NOT NULL,
 Phone_Number VARCHAR(15) NOT NULL,
 Year VARCHAR(4) NOT NULL,
 Email VARCHAR(20) NOT NULL,
 Address TEXT NOT NULL,
 City VARCHAR(20) NOT NULL,
 State_Province VARCHAR(20) NOT NULL,
 ZIP_PostalCode VARCHAR(10) NOT NULL)
 ;

CREATE TABLE salerperson (saler_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (saler_ID),
Staff_ID VARCHAR(5) NOT NULL,
Name VARCHAR(20) NOT NULL,
 Store VARCHAR(20) NOT NULL)
 ;

CREATE TABLE invoices (invoice_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (invoice_ID),
InvoiceNumber VARCHAR(10) NOT NULL,
Date DATE NOT NULL)
 ;
 
 #other parameters of the table were added directly in workbench.alter
 
 